FROM oven/bun:1.3-alpine

WORKDIR /app

# Copy dependency manifests
COPY package.json bun.lock* ./
COPY prisma ./prisma/

# Install dependencies
RUN bun install

# Copy source code
COPY . .

# Expose server port
EXPOSE 3000

# Start server in dev mode with auto db push & hot reload
CMD ["sh", "-c", "bun prisma generate && bun prisma db push && bun dev"]
